### ISSUE TITLE
Tabout with nvim-cmp and LuaSnip

### ISSUE THREAD

**Issue by zetashift** [abecodes/tabout.nvim#13]
I tried to make a similiar function to the current 'nvim-compe vsnip tabout' function, but I'm not getting far and I don't know all the things yet have nvim-cmp.

Are there any tips to get nvim-cmp / LuaSnip and tabout working together?

**Comment by zetashift** [comment]
I got it working but currently in Fennel files I'm running into the following:

```fennel
|(foo)
```

My cursor is at `|` and if I press shift now to tab/indent `(foo)` it tabs out rather than insert whitespace. Anyway to disable that?

**Comment by abecodes** [comment]
Hi @zetashift, I am glad you could fix your issue.
Regarding the second issue, you could try mapping a different key to '<Plug>(Tabout)' so you can preserve tabs shifting. Or you map a key to trigger '<CMD>TaboutToggle', so you can enable/disable Tabout when needed.
I will close the issue, let me know if there is smth else and it needs to be reopened ;)

**Comment by zetashift** [comment]
Ah thank you!

**Comment by IndianBoy42** [comment]
Could you share what the problem was and how you fixed it @zetashift
