### ISSUE TITLE
E31: No such mapping

### ISSUE THREAD

**Issue by piersolenski** [abecodes/tabout.nvim#20]
Hey! I'm getting the following error when trying to install with packer using the default config:

`packer.nvim: Error running config for tabout.nvim: .../site/pack/packer/start/tabout.nvim/lua/tabout/utils.lua:53: E31: No such mapping`

**Comment by abecodes** [comment]
Hi @piersolenski 

thats strange. Thats coming from the unmap function, which is only triggered when tabout is toggled. Do you have `tabout.toggle()` somewhere in your config?

**Comment by piersolenski** [comment]
Nope! I uninstalled, reinstalled it, now it's working. Absolutely no idea where that came from or where it's gone but can close this!
