### ISSUE TITLE
Multiline { or (

### ISSUE THREAD

**Issue by danymat** [abecodes/tabout.nvim#21]
Hello, just trying out this wonderful plugin and I love it. I customized it with:

```lua
		use({
			"abecodes/tabout.nvim",
			config = function()
				require("tabout").setup({
					tabkey = "<C-l>", -- key to trigger tabout, set to an empty string to disable
					backwards_tabkey = "<C-h>", -- key to trigger backwards tabout, set to an empty string to disable
					act_as_tab = false,
				})
			end,
			wants = { "nvim-treesitter" }, -- or require if not used so far
			after = { "nvim-cmp" }, -- if a completion plugin is using tabs load it before
		})
```

I wonder if it would be feasible to tabout from a { or ( that is not on the same line, for example:

```lua
use({ -- cursor here
...
})
```

**Comment by abecodes** [comment]
Hi @danymat

thanks for the kind words 😊  [Multiline tabout](https://github.com/abecodes/tabout.nvim#multiline-tabout) is supported and exposed via the <Plug> api. You could set `tabkey` to some keycombo you are not using and then map `<C-l>` to `<Plug>(TaboutMulti)`.

Let me know if this works for you

**Comment by danymat** [comment]
I will try out, and let you know. thanks !

**Comment by danymat** [comment]
Works wonderfully, thanks !
