### ISSUE TITLE
packer-error: attempt to concatenate upvalue 'completion_binding' (a nil value)

### ISSUE THREAD

**Issue by tim-hilt** [abecodes/tabout.nvim#24]
This started happening earlier today, but somehow only, when I edit a Markdown-file. I don't have completion or Treesitter set up for Markdown, but I remapped the tab-key for Markdown-files in `ftplugin/markdown.lua`.

You can take a look at my config [here](https://github.com/tim-hilt/nvim/blob/main/lua/tim/plugins.lua#L28).

It must have something to do with another plugins update, however I feel a bit lost in debugging this. Would love your insight on the error, maybe you know a solution off the top of your head.

**Comment by abecodes** [comment]
Hi @tim-hilt,

thanks for pointing that out. That seems like an issue on my side 😢 

Would you do me a favour and try [this branch](https://github.com/abecodes/tabout.nvim/tree/fix/24-add_nil_check_for_completion_binding) and let me know, if this fixes the issue?

  use {
    "abecodes/tabout.nvim",
    config = function()
      require("tabout").setup()
    end,
    branch = "24-add_nil_check_for_completion_binding",
    wants = { "nvim-treesitter" },
    after = { "nvim-cmp" }
  }
```

**Comment by tim-hilt** [comment]
Yes, error is gone now! The PR provides a good workaround.
