### ISSUE TITLE
Not working in lua files

### ISSUE THREAD

**Issue by ziombo** [abecodes/tabout.nvim#28]
Tabout works perfectly fine in .js files, but doesn't work for .lua. My config is copied word for word from the example, with one change, 
`after = {'completion-nvim'} -- if a completion plugin is using tabs load it before`
instead of completion-nvim I use nvim-cmp.

**Comment by abecodes** [comment]
Hi @ziombo 

Can you paste me the part of the lua code, so I can double check?

**Comment by abecodes** [comment]
Looks good to me
