### ISSUE TITLE
A leading space is added to each tab in Makefile

### ISSUE THREAD

**Issue by rekaerst** [abecodes/tabout.nvim#35]
Inserting a tab in Makefile with tabout.nvim installed cause a leading space is added before the tab. This caused `make` to fail with error: `missing separator.  Stop.`

## reproduce
- open Makefile
- disable nvim auto indent with `:setl noai nocin nosi inde=` (as tab inserted by auto indent does not have this problem)
- enter and save:
```
main:
 	echo "passed"
```
- Use `cat -etv Makefile`. It shows the presence of tabs with ^I and line endings with $.
```
main:$
 ^Iecho "hello"$
```
- A space is before `^I`

reproduced with minimal setup with only nvim treesiter and tabout.nvim installed.

## system

- nvim version: 0.8.0
- tabout.nvim HEAD: be655cc7ce

**Comment by abecodes** [comment]
@rekaerst thanks for catching this one 🏅 I pushed a fix, can you verify that it is working for you now?

**Comment by rekaerst** [comment]
It works, thank you for your help.
