### ISSUE TITLE
Partial support for tex and markdown

### ISSUE THREAD

**Issue by fecet** [abecodes/tabout.nvim#38]
For markdown, tabout seems entirely not work. In Tex, it successful jump out for `""`,`{}` , `''`, but failed otherwise.

**Comment by abecodes** [comment]
Hi @fecet 

it works for markdown, but only in codeblocks with a language specified:

```go
func xxx(){}
```

I prepared a [branch](https://github.com/abecodes/tabout.nvim/tree/feature/tabout-md) to make it work across the whole markdown, feel free to test is. Does not work correctly with inline code.

I have no idea what tex files are and how they work, in the examples I found online tabout didn't work for anything. But looks like it is not supported by treesitter, at least I never get a node back to work with.

**Comment by fecet** [comment]
Sorry for misunderstanding, "tex files" means "latex" file whose extension is ".tex", nvim-treesitter already support it. And I test it by `nvim a.tex` then type "()", not in a codeblock. I have thought all the filetype that treesitter support can work well with tabout, that's not true?

**Comment by abecodes** [comment]
You are correct, tex should work with treesitter.
Can you post an example of your tex file? I try to test with that one then.

**Comment by fecet** [comment]
```
works:

''
""
``
{}

not work:

()
[]
```

**Comment by abecodes** [comment]
I try to take a look at the weekend, but on first glance it looks like treesitter is not recogizing the node under the cursor. And with no node, tabout will do nothing.
