### ISSUE TITLE
Feature request: jump to next argument

### ISSUE THREAD

**Issue by fjchen7** [abecodes/tabout.nvim#39]
I am using [cmp](https://github.com/hrsh7th/nvim-cmp/wiki) for auto-completion. For method completion `cmp` may complete  arguments together for placeholder.

For example, this is what it look like after completion. The first argument is selected and I can type any key to delete it.

![image](https://user-images.githubusercontent.com/10106636/204094291-4144f363-ea64-4fe4-80e7-f327b5cfacf7.png)

After typing,
![image](https://user-images.githubusercontent.com/10106636/204094523-538a3bcd-98f6-4e5a-a30f-dd8a4e76be3e.png)

What I want is: in the second screenshot, if I presse `<tab>` then cursor jumps to second argument and select it.
- If I type any non-`<tab>` key then I start to replace.
- If I press `<tab>` again, then leave it and jump to next argument.

Actually this is what VSCode does for method completion right now.

**Comment by abecodes** [comment]
Hi @fjchen7,

that is smth that should be handled by cmp for you.
I use [coq](https://github.com/ms-jpq/coq_nvim), which adds markers around each param, so I can jump through and update them.
My guess would be, that any other completion tool should offer smth like that as well.

If this functionality is still needed, I would not mind to accept a PR.
