### ISSUE TITLE
How to install the plugin with vim-plug?

### ISSUE THREAD

**Issue by Gelio** [abecodes/tabout.nvim#4]
Hey, I've been trying to test this plugin out but I am having trouble getting it to work.

I am using https://github.com/junegunn/vim-plug instead of https://github.com/wbthomason/packer.nvim to manage my plugins.

I have added 

```vim
	Plug 'abecodes/tabout.nvim'
```

to my `init.vim` and then below I have

```vim
lua << EOF
require'nvim-treesitter.configs'.setup {
	-- my config here
}
require('tabout').setup {
    tabkey = '<Tab>', -- key to trigger tabout
    act_as_tab = true, -- shift content if tab out is not possible
    completion = true, -- if the tabkey is used in a completion pum
    tabouts = {
		{open = "'", close = "'"},
		{open = '"', close = '"'},
		{open = '`', close = '`'},
		{open = '(', close = ')'},
		{open = '[', close = ']'},
		{open = '{', close = '}'}
	},
    ignore_beginning = true, --[[ if the cursor is at the beginning of a filled element it will rather tab out than shift the content ]]
}
EOF
```

but when opening neovim I am getting this warning https://github.com/abecodes/tabout.nvim/blob/913124629f94b0129686aef039e6ffd2760cb33e/lua/tabout.lua#L60

I suppose the plugin assumes that packer is always used (I assume this is where `package.loaded` is coming from).

Is there a way to run the plugin with vim-plug?

**Comment by megalithic** [comment]
I was having a similar issue with paq.nvim and it looks like you will want to add:
`vim.cmd("packadd nvim-treesitter")` above your `require('tabout').setup {` block.

That _seems_ to have fixed it for me, no more warning printed, at least; will let you know what happens with actual use.

**Comment by abecodes** [comment]
Thanks for your feedback @Gelio 👍 

Can you please check again with this [branch](https://github.com/abecodes/tabout.nvim/tree/feature/issue-4_vim_plug_fix) please?

The warning should be gone and for testing purpose the plugin will not exit.

`package.loaded` should be a general lua method, at least I thought so ;) 

@megalithic Can you also check out the other branch?

**Comment by Gelio** [comment]
@abecodes Thanks :+1: I got tabout installed using the branch you suggested 

```vim
	Plug 'abecodes/tabout.nvim', { 'branch': 'feature/issue-4_vim_plug_fix'}
```

and the warning is gone. Looks like tabout initializes correctly now :+1: 

However, now when pressing tab inside quotes I am getting

```
E15: Invalid expression: !pumvisible() ? "<80><fd>hTabout^M" :
```

when I had `completion = true`, or

```
E15: Invalid expression: <80><fd>hTabout^M
```

when I had `completion = false`. Do you think it's related, or should I create a separate issue?

**Comment by abecodes** [comment]
The first part is nice to hear, the second isn't xD

Can you please create a new issue for that? I will then create a new branch for you ;)

Is it happening only for quotes? Or also parentheses? In which language? Can you post the code example?
It is related to keyboard signals and the escaping of them. The error with `completion = true` will happen, if you have no 'smart-tab' function defined (for example `completion-nvim` or `nvim-compe`). 

Therefore it should™ work with `completion = false`. Since I don't have any standard issues keyboard lying around. I have a hard time testing it. 

So thanks again for your feedback, that will help to get it working 👍

**Comment by Gelio** [comment]
Thanks for the fix :+1: 

I was about to report the issue, but looks like https://github.com/abecodes/tabout.nvim/issues/6 is exactly what I'm facing

**Comment by AGou-ops** [comment]
@Gelio Hey, Geolio.

I have same issue as you, I also use `vim-plug`.
And my config `init.lua` is:
![image](https://user-images.githubusercontent.com/57939102/151097688-721308fa-edf0-463c-afa7-72b144e7bf6c.png)

But It doesn't work when I press `<Tab>` or  `<S-Tab>`.

Can I refer to your nvim dotfile?

**Comment by Gelio** [comment]
@AGou-ops I have switched to https://github.com/wbthomason/packer.nvim as my package manager, so I don't think that would be of use to you

**Comment by AGou-ops** [comment]
> @AGou-ops I have switched to https://github.com/wbthomason/packer.nvim as my package manager, so I don't think that would be of use to you

okay, thank you.
