### ISSUE TITLE
How can I disable jumping from open bracket

### ISSUE THREAD

**Issue by fjchen7** [abecodes/tabout.nvim#40]
Currently the behaviour with `<tab>` are
1. `|{hello}` -> `{hello}|`
2. `|"hello"` -> `"hello"|`
3. `{|hello}` -> `{hello}|`
4. `"|hello"` -> `"hello"|`

I want to disable jump in these scenarios. `ignore_beginning = false, act_as_tab = true` does not work for 3 and 4.

**Comment by abecodes** [comment]
Hi @fjchen7 

Just to better understand:

In which scenarios do you want to jump then?
Only if there is no content?

**Comment by fjchen7** [comment]
Sometimes text is already here, and I want to wrap it with brackets or quotes, and append something after the text. For illustration
1. original text: `hello`
2. wrap it: `"|hello"` (plugins like `nvim-autopairs` can provides wrap functionality)
3. press tab: `"hello|"`
4. append something: `"hello world|"`

But currently  from `"|hello"` pressing tab will jump to `"hello"|`, and I have to move back by arrow key.

**Comment by abecodes** [comment]
Hi @fjchen7 

Sorry for the late answer.

Well, the plugin is called tab**OUT**, so one would expect it to jump out of wrapping symbols 😄 

This seems like kind of an edge case to me, smth you do not want the plugin to do 99% percent of the time.

I could add a switch to enable such a behavior, but feels like you would be better of with a keybinding to `hea` or `f"` for these kind of situations.

Let me know if that helps or if I am missing smth
