### ISSUE TITLE
Why doesn't it tab out of square brackets?

### ISSUE THREAD

**Issue by yanshay** [abecodes/tabout.nvim#43]
In rust code:

`#[derive(Error, Debug)]`

Cursor before 'g', pressing tab moves cursor to after ')' and then further tabs don't progress to after the square brackets.
My configuration includes the square brackets characters.
It doesn't progress beyond square brackets also on other lines.

Is there a reason for that?

**Comment by abecodes** [comment]
Hi @yanshay

Can you try the `feature/tabout-md` branch? If that works, its most likely smth with treesitter.

**Comment by yanshay** [comment]
Still doesn't work with `feature/tabout-md` branch

**Comment by abecodes** [comment]
Do you have a larger snippet?
If I use the above line in a rust file it works as expected and tabs out of both brackets.

Also, for such constructs in rust the correct setting for tabout is `{open = '#', close = ']'}`.

**Comment by yanshay** [comment]
```
fn main() {
    println!("Hello, world!");
}
 
#[derive(Debug)]
struct Name {
    field: String
}

```

Indeed, if I add `{ open = "#", close = "]" }` then it works, but why should it be that way? There's an open square bracket there, shouldn't it tab out of the square brackets w/o that entry?

**Comment by abecodes** [comment]
Nice.

Thats because tabout still uses treesitter and that kind of construct is a node starting at `#` and ending with `]`. So if you only register the brackets, treesitter will not return the `[` as start char but `#`, and tabout ignores it.

**Comment by yanshay** [comment]
Got it, thanks

Where can I find such additional configurations required for specific languages?

**Comment by abecodes** [comment]
@yanshay 

I am working on a rewrite without treesitter, but this will take some time. I guess you need to try and if does not work, have a closer look at the language specifications 🕵️
