### ISSUE TITLE
Standalone setup file

### ISSUE THREAD

**Issue by zcysxy** [abecodes/tabout.nvim#44]
Thanks for this plugin!

When I tried to move the setup config into a standalone lua file like I did for other plugins, an error occurs:

```console
Error detected while processing /Users/ce/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ./tabout.lua:1: loop or previous error loa
ding module 'tabout'
stack traceback:
        [C]: in function 'require'
        ./tabout.lua:1: in main chunk
        [C]: in function 'require'
        /Users/ce/.config/nvim/lua/plugins/tabout.lua:1: in main chunk
        [C]: in function 'require'
        /Users/ce/.config/nvim/lua/plugins/init.lua:9: in main chunk
        [C]: in function 'require'
        /Users/ce/.config/nvim/init.lua:1: in main chunk
```

Here is my config structure

```text
.
├── after
│   └── ftplugin
├── init.lua
└── lua
    ├── init.lua
    └── plugins
        ├── init.lua
        ├── cmp.lua
        ├── ...
        └── tabout.lua
```

I require every files in the plugins directory in the `lua/plugins/init.lua` file.

And here is my tabout config (the example config):

```lua
require'tabout'.setup({
    tabkey = '<Tab>', -- key to trigger tabout, set to an empty string to disable
    backwards_tabkey = '<S-Tab>', -- key to trigger backwards tabout, set to an empty string to disable
    act_as_tab = true, -- shift content if tab out is not possible
    act_as_shift_tab = false, -- reverse shift content if tab out is not possible (if your keyboard/terminal supports <S-Tab>)
    default_tab = '<C-t>', -- shift default action (only at the beginning of a line, otherwise <TAB> is used)
    default_shift_tab = '<C-d>', -- reverse shift default action,
    enable_backwards = true, -- well ...
    completion = true, -- if the tabkey is used in a completion pum
    tabouts = {
      {open = "'", close = "'"},
      {open = '"', close = '"'},
      {open = '`', close = '`'},
      {open = '(', close = ')'},
      {open = '[', close = ']'},
      {open = '{', close = '}'}
    },
    ignore_beginning = true, --[[ if the cursor is at the beginning of a filled element it will rather tab out than shift the content ]]
    exclude = {} -- tabout will ignore these filetypes
})
```

Maybe this is a trivial issue, but since I haven't encountered it before, I have no clue. Thanks for any help!

**Comment by abecodes** [comment]
Hi @zcysxy 
Looks similar to my approach at first glance.
Can you do some test runs?
Start with a completly empty `tabout.lua` file, that should not throw. If it does, something is off in your configs.
Then just add `require'tabout'.setup()` to the file, that should also work. If not, maybe tabout is not installed correctly. And then add your config line by line. After adding a line, start nvim. If it fails here, it may be spelling or a comma...or I messed a function up. Let me know what it is.

**Comment by zcysxy** [comment]
Thanks for the reply @abecodes! Yeah, it works with the empty `taubout.lua`, but a single line `require'tabout'.setup()` throws the error. I install the plugin with Packer:

```lua
    use { 'abecodes/tabout.nvim',
        wants = {'nvim-treesitter'},
        after = {'nvim-cmp'}, }
```

And `PackerStatus` and the plugin folder show `tabout.nvim` correctly. I also tried reinstalling the plugin.

**Comment by abecodes** [comment]
Hmm,
I guess its an issue with the load order then.

If you just install it with packer, remove the `tabout.lua` and run `:lua require'tabout'.setup()` it should work. If you get the `:Tabout` completion, it worked and the load order of your scripts is somehow wrong.

Hope that helps 😊
