### ISSUE TITLE
Tabout stops working after save

### ISSUE THREAD

**Issue by preiter93** [abecodes/tabout.nvim#53]
Hi, I have some issue getting tabout to work. 

It works fine before I save, but it stops working on code that was added after first saving.

Say I write the function hello, then save and then write world then save and the say()
```
    pub fn hello() {}
    pub fn world() {}
    pub fn say() {}
```
It would not tab-out of say (), but it still tabs out from hello and say () 

I use the lazy plugin manager and remapped the tabkey to C-t to rule out conflicts with other packages.

Here is my setup
```
return {
  'abecodes/tabout.nvim',
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "hrsh7th/nvim-cmp",
  },
  opts = {
    -- options = {
    tabkey = '<C-t>',
    backwards_tabkey = '',
    act_as_tab = false,
    act_as_shift_tab = false,
    default_tab = '',
    default_shift_tab = '',
    enable_backwards = true,
    completion = false,
    tabouts = {
      { open = "'", close = "'" },
      { open = '"', close = '"' },
      { open = '`', close = '`' },
      { open = '(', close = ')' },
      { open = '[', close = ']' },
      { open = '{', close = '}' }
    },
    ignore_beginning = true,
    exclude = {}
  },
}
```

any idea what might be the problem?

What i tried so far without success
- Disabling nvim-cmp
- Different programming languages

**Comment by abecodes** [comment]
Hi @preiter93 😊 

What language is this? Do you have a full snippet so I can test?
Sounds like the buffer/treesitter gets not correctly refreshed and the plugin still works on the old version of it...weird.
