### ISSUE TITLE
Tubout inside Rust macro

### ISSUE THREAD

**Issue by kolach** [abecodes/tabout.nvim#58]
I notice incorrect behavior of Tabout inside Rust macro. Let's take a simple oneline example:

```rust
format!("{:x}", hash_result);
```

Suppose `I` signifies cursor position before Tabout command is executed:

```rust
 format!("{:x}|", hash_result)
```

Now I click `Tab` and cursor gets to the end like this:

```rust
format!("{:x}", hash_result)|
```

rather than expect after `"`:

```rust
format!("{:x}"|, hash_result)
```

Is it possible to fix with some configuration?

**Comment by abecodes** [comment]
Hi @kolach ,

totally forgot to answer, sorry :(

Thats how treesitter defines this node for rust. To change that, you could either create a PR to treesitter to change that, or PR to tabout which checks if we use rust, if we are in a makro, and if we are in the string argument. Then we would need some checking of the chars if it is indeed the string argument, etc. 
Feel free to give it a try and create a PR 👍 

Happy holidays and stay healthy
