### ISSUE TITLE
Feature: support for non-treesitter enabled buffers

### ISSUE THREAD

**Issue by pidgeon777** [abecodes/tabout.nvim#62]
I wonder if it could be possibile to enable the tabout feature also for non-treesitter buffers, like this implementation (which doesn't support treesitter):

https://github.com/kawre/neotab.nvim

So the idea would be, if treesitter is available use the current implemented functions. If not, try to guess where the cursor should be placed after the Tabout command.

**Comment by pidgeon777** [comment]
Also, if it is not possible to add this feature directly into `tabout.nvim`, I wonder if it could be possible to leave both plugins active.

When treesitter is not available, tab key should trigger `neotab.nvim`, in the opposite case however it should trigger `neotab.nvim`.

Maybe it would it possible to achieve this, with a specific configuration?

**Comment by abecodes** [comment]
You should be able to write your own tiny plugin/config in `init.lua`.
If you are lucky you can base this of the `filetype` event and check if treesitter is enabled and supports the language, then load `tabout`. If not, load `neotab`. You just need to find a way to "unload" I guess.
