### ISSUE TITLE
Feature request: support nvim-treesitter next version

### ISSUE THREAD

**Issue by towry** [abecodes/tabout.nvim#63]
See:

- https://github.com/nvim-treesitter/nvim-treesitter/tree/main
- https://github.com/nvim-treesitter/nvim-treesitter/issues/4767

**Comment by abecodes** [comment]
@towry Thanks for pointing this out 👍 
@mrcjkb Thanks for doing all the work 🎖️

**Comment by towry** [comment]
@mrcjkb Thanks for your work. 💯
