### ISSUE TITLE
Is the example mappings wrong with "replace_termcodes"?

### ISSUE THREAD

**Issue by lkhphuc** [abecodes/tabout.nvim#65]
I'm trying to setup tabout with native nvim snippet on nvim 0.10 nightly and follow the examples on README.
However, it keeps inserting weird character when I press tab.
After tweaking around, I finally manage to get it running by setting the "special" opts of vim.api.nvim_replace_termcodes(str, true, true, false) , as compared all-true in the example.

I'm not very familiar to nvim internal so I just want to inform this so someone can check and correct the README if it's not correct. For my I got it working so feel free to close this.

Here is my full lazy.nvim config with native snippet:
```lua
  {
    "abecodes/tabout.nvim",
    event = "InsertCharPre",
    opts = { tabkey = "", backward_tabkey = "" },
    keys = {
      {
        "<Tab>",
        function()
          if vim.snippet.jumpable(1) then
            vim.schedule(function() vim.snippet.jump(1) end)
            return
          end
          return vim.api.nvim_replace_termcodes("<Plug>(Tabout)", true, true, false)
        end,
        expr = true,
        mode = "i",
      },
      {
        "<Tab>",
        function()
          vim.schedule(function() vim.snippet.jump(1) end)
        end,
        silent = true,
        mode = "s",
      },
      {
        "<S-Tab>",
        function()
          if vim.snippet.jumpable(-1) then
            vim.schedule(function() vim.snippet.jump(-1) end)
            return
          end
          return vim.api.nvim_replace_termcodes("<Plug>(TaboutBack)", true, true, false)
        end,
        expr = true,
        silent = true,
        mode = { "i", "s" },
      },
    },
  },

```
Thanks for the plugin.

**Comment by abecodes** [comment]
Hi @lkhphuc, thanks for your feedback 👍 
You are correct, I use all true myself.

Do you want to create a PR so you get the fame you deserve?
