### ISSUE TITLE
Recent change disables TAB key in shell files (bash, zsh, etc.) ... (and possibly others?)

### ISSUE THREAD

**Issue by farzadmf** [abecodes/tabout.nvim#68]
Hi there,

I noticed that with the recent change (c442ae7), my TAB key is completely disabled in shell files I'm editing (in my case, it's mostly zsh files).

I see a lot of plugins use the "bleeding edge" APIs; is it possible that the recent change is using APIs that are not compatible with neovim version `0.9` (the version I have)?

Is there any config update I need to do because of the new commit?

**Comment by abecodes** [comment]
Hi @farzadmf 👋 

It seems to work for me in `fish` files.

Just make sure you install all needed language extensions for treesitter.

(do you have a specific codesnippet I could test?)

**Comment by farzadmf** [comment]
Hey @abecodes , so sorry for the late reply

A bit hard for me to prepare a minimal config as I have a million plugins in my config.

I narrowed it down a bit, and it seems like it happens when `ft = zsh`. For example, if I open a `.zsh` file and manually do `set ft=bash`, then `TAB` starts working.

Not sure what's up with `zsh` files (I don't think there's any specific Treesitter parser for it, and it should the "standard" shell parsers maybe).

And, as I mentioned, it happens with the commit I mentioned and not when I go before that commit. Not sure if that helps in anyway, but just mentioning it again

**Comment by abecodes** [comment]
Hi @farzadmf 

I guess this is related to the underlying treesitter implementation then 🤷 
The updated basically switched from og treesitter to the integrated version with nvim. So it should not change anything.

That being said, I see the same behavior in `zsh` files and get the error, that treesitter does not know how to handle `zsh`.
So, the main issue is, that `zsh` is just not supported by treesitter.

You can see if the branch `feature/tabout-md` works for you...basically a stale branch that is still on an old version before said changes 🤞

**Comment by farzadmf** [comment]
> basically a stale branch that ...

@abecodes I think that's not much of an option 🤔 given that, as you said, it's an "stale" branch, so even _if_ it works, I think it's a good idea to use a branch that's up-to-date

> the main issue is, that `zsh` is just not supported by treesitter.

That's sad 🙁
