### ISSUE TITLE
Failed tabout clears the statusline

### ISSUE THREAD

**Issue by smartinellimarco** [abecodes/tabout.nvim#70]
When attempting to do a tabout (and failing), for some reason the statusline (lualine) disappears.

**Comment by abecodes** [comment]
Hi @smartinellimarco,

do you have a codesnippet? I use lualine myself and never encountered this oO

**Comment by smartinellimarco** [comment]
Here is a minimal example (note the cmdheight=0 setting):
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)
vim.opt.cmdheight = 0

-- install plugins
local plugins = {
	{
		"nvim-lualine/lualine.nvim",
		opts = {
			options = {
				globalstatus = true,
				component_separators = "",
				section_separators = "",
			},
			sections = {
				lualine_a = { "mode" },
				lualine_b = { { "filename", path = 1 } },
				lualine_c = { "branch", "diagnostics" },
				lualine_x = { "encoding" },
				lualine_y = { "progress" },
				lualine_z = { "location" },
			},
		},
	},
	{
		"abecodes/tabout.nvim",
		opts = {
			act_as_tab = false,
			act_as_shift_tab = false,
			enable_backwards = true,
			completion = false,
			tabouts = {
				{ open = "'", close = "'" },
				{ open = '"', close = '"' },
				{ open = "`", close = "`" },
				{ open = "(", close = ")" },
				{ open = "[", close = "]" },
				{ open = "{", close = "}" },
			},
			exclude = {},
		},
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

```

**Comment by abecodes** [comment]
I do not have/use lazy, but if I run this file with `vim.opt.cmdheight = 0` and do the `<S-TAB>` in an indentation area the lualine disappears until the next keypress. Is this the behavior you are experiencing?

This does not happen with `vim.opt.cmdheight = 2`. After googling a little looks like there are some issues with nvim, statuslines in general and `vim.opt.cmdheight = 0`, eg [here](https://github.com/neovim/neovim/issues/26875) or [here](https://github.com/neovim/neovim/pull/20644) and [something similar](https://github.com/nvim-lualine/lualine.nvim/issues/1044).

I get the feeling that `vim.opt.cmdheight = 0` is an either or thing and this is nothing we can fix in tabout.
So I guess it is either `vim.opt.cmdheight = 1/2` or no/flickering statusline 😢
