### ISSUE TITLE
no parser found for filetype NeogitCommitMessage

### ISSUE THREAD

**Issue by uwla** [abecodes/tabout.nvim#74]
Hello!

When using this plugin, it does not work inside git commit message to tabout of parenthesis, quotes, etc.

If I put parenthesis or quotes in the git commit message (I'm using NeoGit plugin), I'd expect tabout to work, but it shows this error instead:

```
tabout.nvim: No parser found for filetype NeogitCommitMessage
```

**Comment by abecodes** [comment]
Hi @uwla,

This is expected since `NeogitCommitMessage` is not anything that is supported by `treesitter` .
Which is a bummer, since I love Neogit 😊

**Comment by abecodes** [comment]
Hi @uwla 

I was experimenting with sth like this but it is not very trivial...at least if you want to jump to the next relevant delimiter.
