### ISSUE TITLE
Tabout.nvim interferes with LSP parameter hints deletion

### ISSUE THREAD

**Issue by ralph-bergmann** [abecodes/tabout.nvim#76]
Expected behavior:
- LSP parameter hints appear when selecting a method
- Parameter hints automatically disappear when typing custom parameters

Current behavior:
- LSP parameter hints appear when selecting a method
- When using tabout.nvim, parameter hints persist even after typing custom parameters

Steps to reproduce:
1. Open a file with LSP support enabled
2. Type a method name and select it from LSP suggestions
3. Observe parameter hints appear
4. Try typing custom parameters
5. Parameter hints remain visible instead of being cleared

Question:
Is there a way to maintain both tabout.nvim functionality and proper LSP parameter hints behavior?

**Comment by abecodes** [comment]
Hi @ralph-bergmann 

Thats a great description 🎖️ 

This is a case I never considered, mea culpa.

In the current state there is no way to fix this, but I think I can add an `tabbedOut` event, so you can listen to that and refresh the lsp hints when it occurs.

**Comment by abecodes** [comment]
@ralph-bergmann 
see https://github.com/abecodes/tabout.nvim/blob/master/README.md#-hooks

This will enable you using both behaviors 👍
